
version: 2
updates:

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    labels:
      - "github-actions"
      - "dependencies"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    labels:
      - "github-actions"
      - "dependencies"

  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    labels:
      - "gradle"
      - "dependencies"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/backend/deployment"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Zurich"
    target-branch: "main"
    labels:
      - "docker"
      - "dependencies"
