blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://github.com/umb/curo/wiki
    about: You can find answers to common questions on our Wiki. Make sure to read the FAQ page!
  - name: Releases
    url: https://github.com/umb/curo/releases
    about: You can find the latest releases here on GitHub.
