curo:
  print-stacktrace: false
  camunda-telemetry: false
  auth:
    type: oauth2
    oauth2:
      verify-jwt: false
      user-id-claim: email
      allowed-issuers:
        - https://keycloak-curo-demo.apps-dev.umb.cloud/auth/realms/curo
      print-errors-to-log: true
      user-federation:
        enabled: true
        resource-name: curo
  camunda-user-id-pattern: '[a-zA-Z0-9-.@_]+'
