name: ng CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/**"

defaults:
  run:
    working-directory: frontend

env:
  node-version: 14.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}
      - run: npm ci
      - run: npm run test.ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}
      - run: npm ci
      - run: npm run build
#  containerize:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v2
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
